baseurl = "https://erocoar.github.io/"
title = "Pi*Thumb"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Frederik Tiedemann"
canonifyurls = true
googleAnalytics = "UA-111592073-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[Author]
    name = "Frederik Tiedemann"
	
[Taxonomies]
    tag = "tags"
	
[Params]
    intro = true
    headline = "Blog"
    description = ""
    github = "https://github.com/erocoar"
    linkedin = "https://www.linkedin.com/in/frederik-tiedemann-67291396/"
    stackoverflow = "https://stackoverflow.com/users/5508500/erocoar"
    email = "fj.tiedemann@googlemail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"
	



